version: '3'

services:
  db:
    image: mysql:9
    volumes:
      - ./db2:/var/lib/mysql
    env_file:
      - .env.local
    ports:
      - "3306:3306"
  web:
    container_name: sunnah-com-flask
    depends_on:
      - "db"
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    env_file:
      - .env.local
